### ISSUE TITLE
Another path for images

### ISSUE THREAD

**Issue by Labelsuisse** [mirko-pagliai/cakephp-thumber#20]
Hello, 
I have a problem when my image directory is not in img. 
Would it be possible to define the source directory? 
Or detect if the path of the image begins with a /; 
If true the path would be **WWW_ROOT. '/presonnal_upload_path'. DS. 'my_image.jpg'**.
Thank you et great job

**Comment by mirko-pagliai** [comment]
Hello. In any case, you can use absolute paths.

See [here](https://github.com/mirko-pagliai/cakephp-thumber/wiki/How-to-uses-the-ThumbCreator-utility#basic-operation). For all methods, the path can be:

* a relative path (to `APP/webroot/img`);
* a relative path using [plugin syntax](http://book.cakephp.org/3.0/en/appendices/glossary.html#term-plugin-syntax);
* a full path;
* a remote url.

I will evaluate if (in a future release) let you set a different directory when using relative paths.

Let me know if you have any problems even using absolute paths.

**Comment by mirko-pagliai** [comment]
You can also see examples in tests:
https://github.com/mirko-pagliai/cakephp-thumber/blob/master/tests/TestCase/Utility/ThumbCreatorTest.php#L156
