### ISSUE TITLE
Image background black > white

### ISSUE THREAD

**Issue by todi1979** [mirko-pagliai/cakephp-thumber#29]
Convert the black background to a white color

**Comment by mirko-pagliai** [comment]
Sorry, I can not understand. Is it a request? A proposal? A bug? What and why?

**Comment by todi1979** [comment]
Oh, Sorry! This is a request

**Comment by mirko-pagliai** [comment]
Please can you explain exactly what you are proposing and why you are
proposing it?

Il mer 7 mar 2018, 22:45 todi1979 <notifications@github.com> ha scritto:

**Comment by todi1979** [comment]
Black background image:
 [http://dev.teamfitness.hu/thumbs/c5b480b1c7538da081003ca3927964aa_0b3572e7c6a6a2d2137cffb408f72cda.jpg](url)

imagefill($image_resource, 0, 0, imagecolorallocate($image_resource, **255, 255, 255**));  // white background;

**Comment by mirko-pagliai** [comment]
Url is right?

Il mer 7 mar 2018, 23:27 todi1979 <notifications@github.com> ha scritto:

**Comment by todi1979** [comment]
[http://dev.teamfitness.hu/thumbs1/c6e6c4c3a75d489bb8137edc179c2749_0e37b1f4f4448fbf66e0c194336d4159.jpg](url)

**Comment by todi1979** [comment]
Only cropped image

**Comment by mirko-pagliai** [comment]
Please, can you explain what you would like?  
This is the ninth message and I have not understood anything yet.
Please make an effort.

**Comment by todi1979** [comment]
If I crop the picture, the empty background will be black. I would like white background. Please see the attached picture,

Orig photo: 
![img_nature_wide](https://user-images.githubusercontent.com/12648667/37161873-227f486a-22f4-11e8-826c-bffc1eabda44.jpg)

Cropped photo: 
![c6e6c4c3a75d489bb8137edc179c2749_0e37b1f4f4448fbf66e0c194336d4159](https://user-images.githubusercontent.com/12648667/37161846-10719812-22f4-11e8-9cd3-5994b5f06c37.jpg)

**Comment by mirko-pagliai** [comment]
Ok, now it starts to be clear. 
Can you post the code you used to generate that image?

**Comment by todi1979** [comment]
`<?php echo str_replace(ROOT.'/tmp', '', $this->Thumb->cropUrl($this->Thumb->resizeUrl('../'.$item->file, ['width'=>1900, 'height'=>630, 'upsize'=>false]), ['width'=>1900, 'height'=>630, 'format'=>'jpg', 'fullBase'=>false]));?>`

**Comment by mirko-pagliai** [comment]
It looks a little different. First you make a resize, then you make a crop to a size greater than the original. This plugin was not born to do this.  
This is not a drawing tool, but a tool for creating thumbnails.

In fact, I think the "normal" behavior should be that it throws an exception when you try to make a crop to a greater size than the original, not that it allows you to do it.

Have you tried using the [resizeCanvas()](https://github.com/mirko-pagliai/cakephp-thumber/wiki/How-to-uses-the-ThumbCreator-utility#resizecanvas) method? It allows you to set a background color.
