### ISSUE TITLE
Namespace incorrect in Command files

### ISSUE THREAD

**Issue by jmwmulle** [mirko-pagliai/cakephp-thumber#50]
Line 20 of both ClearAllCommand.php & ClearCommand.php reads

`use MeTools\Console\Command;`

should be

`use Cake\Console\Command;`

Cake console doesn't function otherwise.

**Comment by mirko-pagliai** [comment]
The problem appears to be in the `composer.json` file.  The `mirko-pagliai/me-tools` package should be in the `require` section, instead it is in the `require-dev` section.
I will fix it. For now, try installing the packages manually

**Comment by jmwmulle** [comment]
Yup, `composer require mirko-pagliai/me-tools` solved it, ty.
