### ISSUE TITLE
Getting fatal error on using thumber.

### ISSUE THREAD

**Issue by rahimnagori** [mirko-pagliai/cakephp-thumber#55]
I'm using thuber with cakephp 3.7.
Here is the error I'm getting :

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 28672 bytes)

I'm using it this way : 
```
$thumber = new ThumbCreator($file['tmp_name']);
$thumber->resize(200);
$thumbnail = $thumber->save(['target' => $filename]);
```
and getting the error on save().
Any help with this? I really need the solution.

**Comment by mirko-pagliai** [comment]
I'm sorry, but I was out on vacation.  In the end what was the problem?

**Comment by rahimnagori** [comment]
Actually it was not the problem with the plugin. Problem was at my end. I resolved it myself.
Detail of the problem : 
I was trying to upload a big size image.
Updating values in `upload_max_filesize` and `post_max_size` solved my problem.
Thank you.
