### ISSUE TITLE
Cakephp 4 load plugin and helper

### ISSUE THREAD

**Issue by JRobich** [mirko-pagliai/cakephp-thumber#67]
For cakephp 4 to load the plugin in Application.php:
`$this->addPlugin('Thumber/Cake'); 
        if (!extension_loaded('imagick')) {
            Configure::write('Thumber.driver', 'gd');
        }
        Configure::write('Thumber.target', TMP . 'thumbs');`

Load the Helper in AppView.php
`$this->loadHelper('Thumb', ['className' => 'Thumber/Cake.Thumb']);`

**Comment by mirko-pagliai** [comment]
Hello @JRobich, is a question? I can't understand.

You don't need to set the driver and the destination directory, those are the default values already set by [the bootstrap file](https://github.com/mirko-pagliai/cakephp-thumber/blob/master/config/bootstrap.php).

**Comment by JRobich** [comment]
Ciao mirko, dal tuo nome sono sicuro che sei italiano... ho scritto al volo questa cosa visto che seguendo la documentazione non sono riuscito a installare il plugin.

quando si esegue questo comando:
`bin/cake plugin load Thumber`
il plugin viene caricato con il nome sbagliato e non funziona

colgo l'occasione anche per ringraziarti per il tuo lavoro. Bravo! :)

**Comment by mirko-pagliai** [comment]
Hai ragione, un po' di tempo fa ho cambiato il namespace del plugin (che prima era `Thumber`, ora (`Thumber\Cake`).

Se esegui `bin/cake plugin load Thumber\Cake` (provando, eventualmente, anche a invertire la barra, che nel terminale potrebbe essere interpretata come carattere di escape)? Potresti fare questa prova?

**Comment by JRobich** [comment]
ci ho provato:
`bin/cake plugin load Thumber\Cake`
output
`$this->addPlugin('ThumberCake');`

oppure
`bin/cake plugin load Thumber/Cake`
output
`$this->addPlugin('Thumber/Cake');`

questo è il comando giusto:
`bin/cake plugin load Thumber/Cake`

**Comment by mirko-pagliai** [comment]
@JRobich perfetto, grazie.

**Comment by JRobich** [comment]
a te!

**Comment by Lazza** [comment]
`$this->loadHelper('Thumb', ['className' => 'Thumber/Cake.Thumb']);`

Quesro sarebbe ottimo se fosse nella doc, non era chiarissimo dalle istruzioni. :D

**Comment by mirko-pagliai** [comment]
> ```
> $this->loadHelper('Thumb', ['className' => 'Thumber/Cake.Thumb']);
> ```
> 
> Quesro sarebbe ottimo se fosse nella doc, non era chiarissimo dalle istruzioni.

Non l'ho inserito semplicemente perché ho pensato che se stai utilizzando/per utilizzare un helper, tu abbia messo in conto che lo stesso vada caricato come qualsiasi altro helper.
Insomma, detto diversamente, non è una particolarità o una procedura specifica del plugin.

Comunque non mi costa nulla e a scanso di equivoci provvederò a inserire ;-)

**Comment by Lazza** [comment]
Probabilmente è colpa mia, copiando dal 3 dove avevo scritto:

    $this->loadHelper('Thumber.Thumb');

Mi sono un attimo bloccato, poi ho capito che bastava cambiare il namespace così:

    $this->loadHelper('Thumber/Cake.Thumb');

Diciamo che per "velocità di esecuzione" quando uno non si ricorda al volo, è più pratico poterlo copiare dalla doc. 😁

**Comment by mirko-pagliai** [comment]
Updated the wiki:
https://github.com/mirko-pagliai/cakephp-thumber/wiki/How-to-use-the-helper
