### ISSUE TITLE
Problema bake crud

### ISSUE THREAD

**Issue by JRobich** [mirko-pagliai/cakephp-thumber#88]
Ciao Mirko,

quando provo a fare un bake il terminale mi restituisce un errore:

```
Robin-Hood:cakephp4.x roberto$ bin/cake bake all posts --prefix admin --theme Backend
[Error] Class 'MeTools\Console\Command' not found in /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/mirko-pagliai/cakephp-thumber/src/Command/ClearAllCommand.php on line 28

Stack Trace:

#0 /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/composer/ClassLoader.php(571): include()
#1 /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/roberto/...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Thumber\\Cake\\Co...')
#3 [internal function]: spl_autoload_call('Thumber\\Cake\\Co...')
#4 /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/cakephp/bake/src/Plugin.php(144): ReflectionClass->__construct('Thumber\\Cake\\Co...')
#5 /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/cakephp/bake/src/Plugin.php(97): Bake\Plugin->findInPath('Thumber\\Cake\\Co...', '/Users/roberto/...')
#6 /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/cakephp/bake/src/Plugin.php(73): Bake\Plugin->discoverCommands(Object(Cake\Console\CommandCollection))
#7 /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/cakephp/cakephp/src/Http/BaseApplication.php(237): Bake\Plugin->console(Object(Cake\Console\CommandCollection))
#8 /Users/roberto/Sites/_Frameworks/cakephp4.x/vendor/cakephp/cakephp/src/Console/CommandRunner.php(144): Cake\Http\BaseApplication->pluginConsole(Object(Cake\Console\CommandCollection))
#9 /Users/roberto/Sites/_Frameworks/cakephp4.x/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#10 {main}
```

Questo problema si presenta con la versione di me-tools 2.23.1 mentre non si presenta con la versione 2.22.2

puoi controllare? grazie mille

**Comment by JRobich** [comment]
Ho notato che manca la cartella scr/Console (in me-tools) quindi non trova il namespace...

**Comment by mirko-pagliai** [comment]
Ciao @JRobich il codice è rimasto un po' indietro rispetto alle sue dipendenze, in qualche giorno, magari anche domani, conto di sistemare.

**Comment by JRobich** [comment]
Ciao @mirko-pagliai grazie mille ti sarei molto grato se quando hai sistemato tu potessi avvertirmi.

Quale pensi sia poi il miglio modo da parte mia per sistemare tutto? Rimuovere tramite composer e poi reinstallare?

**Comment by mirko-pagliai** [comment]
@JRobich bisognerebbe sapere cosa stai facendo. Aggiornando un progetto che usa questo pacchetto e installando qualcosa ex-novo? Nel secondo caso, sarà sufficiente installare la nuova release; nel primo, bisognerà verificare appena possibile, se è sufficiente aggiornare, ma immagino di sì

**Comment by JRobich** [comment]
Io sto creando una versione di Cakephp 4 personalizzata in modo tale da poterla utilizzare ogni volta che devo fare un nuovo progetto... Sto quasi pensando di inserire in git anche la cartella vendor e utilizzare composer solo per installare plugin ad hoc per il tipo di progetto che devo fare. In questo modo non posso incorrere in problemi di questo tipo. Che ne pensi? Ogni consiglio è ben accetto :)

**Comment by mirko-pagliai** [comment]
Prova la nuova release [1.11.0](https://github.com/mirko-pagliai/cakephp-thumber/releases/tag/1.11.0) e dammi un riscontro appena possibile

**Comment by JRobich** [comment]
Funziona! grazie mille!
